spring.application.name=javaloginapp

# MySQL Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/java_login_db}
spring.datasource.username=${DB_USERNAME:javaapp}
spring.datasource.password=${DB_PASSWORD}

# JSP
spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp
